- name: Change time zone
  timezone:
    name: "{{time_zone}}"

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist
    update_cache: yes
  become: yes

- name: Update all packages to latest versions
  apt:
    name: "*"
    state: latest
    update_cache: yes
  become: yes

- name: Install RustUp
  shell: |
    set -o pipefail
    curl https://sh.rustup.rs -sSf | sh -s -- -y

- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https

- name: Add Yarn apt key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn

- name: Install Yarn
  apt:
    name: yarn