- name: update system
  include: "update.yml"

- name: download installer rustup
  get_url:
    url: https://static.rust-lang.org/rustup.sh
    dest: "/root/rustup.sh"
    mode: "750"
    validate_certs: no

- name: run installer rustup
  command:
    cmd: ./rustup.sh -y
    chdir: "/root"
    creates: "/usr/local/bin/cargo"
  environment:
    CARGO_HOME: "/usr/local"
    TMPDIR: "/root"

- name: ensure apt-transport-https is installed
  apt:
    name: apt-transport-https

- name: add yarn apt key
  apt_key:
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"

- name: add yarn repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn

- name: install yarn
  apt:
    name: yarn

## TODO: add config for restart
# - name: Reboot immediately if there was a change
#   shell: "sleep 5 && reboot"
#   async: 1
#   poll: 0

# - name: wait for the reboot to complete if there was a change
#   wait_for_connection:
#     connect_timeout: 20
#     sleep: 5
#     delay: 5
#     timeout: 300

# test this, may need to add license to radicle-bins/seeds/ui/package.json
- name: clone radicle repo
  git:
    repo: https://github.com/radicle-dev/radicle-bins.git
    dest: "/home/ansible/repos/radicle-bins/"
    clone: yes
    update: yes

- name: build radicle ui
  shell: "yarn && yarn build"
  args:
    chdir: "/home/ansible/repos/radicle-bins/seed/ui"

- name: create directory for seed data
  file:
    path: "/home/ansible/.radicle-seed"
    state: directory

- name: generate private key
  shell: "cargo run -p radicle-keyutil -- --filename /home/ansible/.radicle-seed/secret.key"
  become: yes
  args:
    chdir: "/home/ansible/repos/radicle-bins"

- name: change secret key permissions
  file:
    path: "/home/ansible/.radicle-seed/secret.key"
    state: file
    owner: root
    group: root
    mode: "0775"

- name: run seed node
  shell: |
    cargo run -p radicle-seed-node --release -- \
    --root /home/ansible/.radicle-seed \
    --peer-listen 0.0.0.0:12345 \
    --http-listen 0.0.0.0:80 \
    --name "{{hostname}}" \
    --public-addr "{{public_addr}}" \
    --assets-path seed/ui/public \
    < /home/ansible/.radicle-seed/secret.key
  become: yes
  args:
    chdir: "/home/ansible/repos/radicle-bins"
