- name: Change time zone
  timezone:
    name: "{{time_zone}}"

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist
    update_cache: yes
  become: yes

- name: Update all packages to latest versions
  apt:
    name: "*"
    state: latest
    update_cache: yes
  become: yes

- name: install build-essentials for cargo
  apt:
    name: build-essentials

- name: install cmake
  apt:
    name: cmake